return {
    ["极速传奇"] = "https://raw.githubusercontent.com/YunLua/Lua/main/极速传奇.lua",
    ["在披萨店工作"] = "https://raw.githubusercontent.com/YunLua/Lua/main/在披萨店工作.lua",
    ["在森林中的99夜"] = "https://raw.githubusercontent.com/YunLua/Lua/main/99.lua",
    ["忍者传奇"] = "https://raw.githubusercontent.com/YunLua/Lua/main/忍者传奇.lua",
    ["吃掉世界"] = "https://raw.githubusercontent.com/YunLua/Lua/main/吃掉世界.lua",
    ["火箭模拟器"] = "https://raw.githubusercontent.com/YunLua/Lua/main/火箭模拟器.lua",
    ["自然灾害生存游戏"] = "https://raw.githubusercontent.com/YunLua/Lua/main/自然灾害生存游戏.lua",
    ["虫脸"] = "https://raw.githubusercontent.com/YunLua/Lua/main/虫脸.lua",
    ["动漫明星模拟器"] = "https://raw.githubusercontent.com/YunLua/Lua/main/动漫模拟器.lua",
    ["蜂群模拟器"] = "https://raw.githubusercontent.com/YunLua/Lua/main/蜂群模拟器.lua",
    ["SCP角色扮演"] = "https://raw.githubusercontent.com/YunLua/Lua/main/SCP角色扮演.lua",
    ["小猪"] = "https://raw.githubusercontent.com/YunLua/Lua/main/小猪.lua",
    ["闯入(故事)[Break in 1(Story)]"] = "https://raw.githubusercontent.com/YunLua/Lua/main/Break_in_1(Story).lua",
    ["在工作申请中存活"] = "https://raw.githubusercontent.com/YunLua/Lua/main/在工作申请中存活.lua",
    ["夜光[恐怖]"] = "https://raw.githubusercontent.com/YunLua/Lua/main/夜光[恐怖].lua",
    ["田野之旅Z[Field Trip Z]"] = "https://raw.githubusercontent.com/YunLua/Lua/main/田野之旅Z.lua",
    ["巴掌模拟器"] = "https://raw.githubusercontent.com/YunLua/Lua/main/巴掌模拟器.lua",
    ["感染性微笑"] = "https://raw.githubusercontent.com/YunLua/Lua/main/感染性微笑.lua",
    ["丹迪的世界"] = "https://raw.githubusercontent.com/YunLua/Lua/main/丹迪的世界.lua",
    ["鲨口求生2"] = "https://raw.githubusercontent.com/YunLua/Lua/main/鲨口求生2.lua",
    ["杀手VS警长"] = "https://raw.githubusercontent.com/YunLua/Lua/main/杀手VS警长.lua",
    ["Fisch"] = "https://raw.githubusercontent.com/YunLua/Lua/main/Fisch.lua",
    ["正在寻求"] = "https://raw.githubusercontent.com/YunLua/Lua/refs/heads/main/ATM.lua"
}
